typography_spectrum: 0.8371298459824175
color:
  brandStrength: 0.5192968447227031
  lightness: 0.9768964236136526
  saturation: 0.3421725353691727
  rhythmicContrast: 0.46920143673196435
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.38939807144925
analytics:
  google: UA-30551785-1
author:
  name: Anton Dee
  url: 'http://www.thestyledivision.com/'
name: Division Collective
navigation:
  - name: STYLE DIVISION
    url: 'http://www.thestyledivision.com/'
    type: external
  - name: TECH DIVISION
    url: 'http://www.thestyledivision.com/future-technology-magazine-blog'
    type: external
  - name: CREATIVE DIVISION
    url: 'http://www.thestyledivision.com/visual-creative-journal'
    type: external
description: Test
